---
- name: 1. install Apache
  apt: name=apache2 update_cache=yes state=present

- name: 2. Start Apache
  service: name=apache2 state=running enabled=yes

- name: 3. install PHP module for Apache
  apt: name=libapache2-mod-php5 state=present

- name: 4. Install PHP GD library
  apt: name=php5-gd state=latest
  notify: 
       - Restart Apache

