---
- name: copy .my.cnf file with root password credentials
  template: src=/etc/mysql/debian.cnf dest=/root/.my.cnf owner=root mode=0600

- name: Create the Drupal user
  mysql_user: >
    name=drupal_user
    password="drupal_db_password"
    priv=*.*:ALL,GRANT
    state=present
